#!/usr/bin/perl -w
use strict;
die usage() unless @ARGV == 1;
open F,$ARGV[0] or die;
while(<F>){
	next if !/^chr/;
        #chr1    717     .       A       G     
	my @tem=split;
        next if $tem[4] =~ /\,/;
	#my ($gt58,$dp58)=$tem[-4]=~/(\d\/\d)\:\d+\,\d+\:(\d+)\:/;
        my ($gt58, $AF58 ,$dp58) = (split(/:/, $tem[-4]));
	if($tem[-4] =~ /\.\/\./){
            $gt58="0/0";
            $dp58=0;
        }else{
            my ($AF58_1, $AF58_2) = split(/,/, $AF58);
            next if ($AF58_1 != 0 && $AF58_2 != 0);
        }
        
        #my ($gt5003,$dp5003) = $tem[-3] =~ /(\d\/\d)\:\d+\,\d+\:(\d+)\:/;
        my ($gt5003, $AF5003,$dp5003) = (split(/:/, $tem[-3]));
        if($tem[-3] =~ /\.\/\./){
            $gt5003="0/0";
            $dp5003=0;
        }else{
            my ($AF5003_1, $AF5003_2) = split(/,/, $AF5003);
            next if ($AF5003_1 != 0 && $AF5003_2 != 0); 
        }
        #my ($gt478,$dp478) = $tem[-2] =~ /(\d\/\d)\:\d+\,\d+\:(\d+)\:/;
        my ($gt478, $AF478, $dp478) = (split(/:/, $tem[-2]));
        if($tem[-2] =~ /\.\/\./){
            $gt478="0/0";
            $dp478=0;
        }else{
            my ($AF478_1, $AF478_2) = split(/,/, $AF478);
            next if ($AF478_1 != 0 && $AF478_2 != 0);
        }
        #my ($gt8112,$dp8112)=$tem[-1]=~/(\d\/\d)\:\d+\,\d+\:(\d+)\:/;
        my ($gt8112, $AF8112, $dp8112) = (split(/:/, $tem[-1]));
        if($tem[-1] =~ /\.\/\./){
            $gt8112="0/0";
            $dp8112=0;
        }else{
            my ($AF8112_1, $AF8112_2) = split(/,/, $AF8112);
            next if ($AF8112_1 != 0 && $AF8112_2 != 0);
        }

	next if ($dp5003 < 5 || $dp8112 < 5 || $dp478 < 5 || $dp58 < 5);
	next if ($gt5003 eq $gt8112);
	next if ($gt478 eq "0/1" || $gt5003 eq "0/1" || $gt8112 eq "0/1" || $gt58 eq "0/1");
        if($gt5003 eq "0/0"){
            $gt5003 = $tem[3];
        }else{
            $gt5003 = $tem[4];
        }
        if($gt8112 eq "0/0"){
            $gt8112 = $tem[3];
        }else{
            $gt8112 = $tem[4];
        }
	print "$tem[0]\t$tem[1]\t$gt5003\t$gt8112\n";
}
close F;

sub usage{
    my $die = <<DIE;
    perl *.pl <vcf> vcf file are generated by gatk 2.7.0
    vcf file: z58,5003,478,8112
    criteria:1) depth in all 4lines no less than 5; 2) either allele eq zero; 3) 
DIE
}
