#!/usr/bin/perl -w
use strict;
die usage() unless @ARGV==1;
my ($rep)=@ARGV;
open RE,$rep or die "$!";
my %umTE_nu;my %TE_nu;
while(<RE>){
    next if /NA/;
    chomp;
    my ($meth,$dis)=(split(/\t/))[-2,-1];
    $dis=int($dis/500+1) if $dis!=0;
    $dis=$dis*500;
    $TE_nu{"$dis"}++;
    $umTE_nu{"$dis"}++ if $meth>=0.1;
}

foreach(sort{$a<=>$b}keys %TE_nu){
    my $propo=$umTE_nu{$_}/$TE_nu{$_};
    print "$_\t$propo\n";
}

sub usage{
    my $die=<<DIE;

    perl *.pl <File generated by TE_meth.pl> 
    We use this to get the propotion of unmethylated TEs in 500bp windows of increasing distanse from gene.
    
DIE
}
