#!/usr/bin/perl -w
use strict;
my ($te_mth,$geno)=@ARGV;
die usage() unless @ARGV==2;
open GENO,$geno or die "$!";
my @aa=<GENO>;
my $join=join'',@aa;
   $join=~s/>//;
   @aa=split(/>/,$join);
   $join="1";  #empty $join
my $chr_nu=@aa;
my %hash;
for(my $i=0;$i<=$chr_nu;++$i){
    next if !$aa[$i];
    my ($chr,@seq)=split(/\n/,$aa[$i]);
    chomp @seq;
    my $tem_seq=join'',@seq;
    $hash{$chr}=$tem_seq;
    $tem_seq="";
}

open MTH,$te_mth or die "$!";
while(<MTH>){
    chomp;
    my ($chr,$stt,$end)=split(/\t/,$_);
    $chr="chr".$chr;
    my $tem_seq=substr($hash{$chr},$stt-1,$end-$stt+1);
    my $c+=$tem_seq=~s/C/C/g;
       $c+=$tem_seq=~s/G/G/g;
    print "$_\t$c\n";
}

sub usage{
    my $die=<<DIE;
    perl *.pl <TE meth> <Geno>
    To use this scripts based on files generated by [TE_gener_meth_info.pl] to get C number of each TEs
DIE
}
